import React from "react";
import { Link } from "react-router-dom";

export default function Terms() {
  return (
    <div className="p-8 max-w-4xl mx-auto font-sans text-[#1E293B] bg-white min-h-screen">
      <h1 className="text-3xl font-bold mb-6 text-yellow-400">Terms of Service</h1>
      <p className="mb-4 text-yellow-400">
        Welcome to Archalize. By using our platform, you agree to the following terms and conditions. If you do not agree, please do not use the service.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2 text-yellow-400">1. Use of the Service</h2>
      <p className="mb-4">
        Archalize provides AI-powered architectural critique based on user-uploaded images. You agree to use the platform responsibly and only upload content you have the rights to share.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2 text-yellow-400">2. User Accounts</h2>
      <p className="mb-4">
        You are responsible for maintaining the confidentiality of your login credentials and any activity that occurs under your account.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2 text-yellow-400">3. Intellectual Property</h2>
      <p className="mb-4">
        All content generated by our AI is provided for personal, non-commercial use. Archalize retains ownership of the underlying platform and technology.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2 text-yellow-400">4. Termination</h2>
      <p className="mb-4">
        We reserve the right to terminate access for violations of these terms or misuse of the platform.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2 text-yellow-400">5. Changes</h2>
      <p className="mb-4">
        We may update these terms at any time. Continued use of the service after updates constitutes agreement to the new terms.
      </p>
      <nav className="absolute top-4 left-6 z-10">
              <Link to="/" className="flex items-center gap-2 text-[#1E293B] hover:text-yellow-400 transition">
                <span className="text-2xl">←</span>
                <span className="text-sm font-medium">Home</span>
              </Link>
            </nav>
    </div>
  );
}
