import React from "react";
import { Link } from "react-router-dom";

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#E5E7EB] text-[#1E293B] font-sans">
      <div className="absolute inset-0 z-0 pointer-events-none">
            <svg
              className="absolute top-0 left-0 w-full h-full"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 1000 2000"
              preserveAspectRatio="xMidYMid slice"
            >
              <defs>
                <pattern id="grid" width="60" height="60" patternUnits="userSpaceOnUse">
                  <path d="M 60 0 L 0 0 0 60" fill="none" stroke="#1E293B" strokeWidth="1" />
                </pattern>
              </defs>

              <rect width="1000" height="2000" fill="url(#grid)" opacity="0.06" />

              {/* Ellipses — centered at 500, 1000 (middle of SVG) */}
              <ellipse cx="500" cy="1000" rx="250" ry="250" stroke="#1E293B" strokeWidth="1" opacity="0.03" />
              <ellipse cx="500" cy="1000" rx="350" ry="350" stroke="#1E293B" strokeWidth="1" opacity="0.02" />
              <ellipse cx="500" cy="1000" rx="450" ry="450" stroke="#1E293B" strokeWidth="1" opacity="0.01" />
            </svg>

          </div>
      <div className="p-8 max-w-4xl mx-auto ">
        <h1 className="text-3xl font-bold mb-6 text-yellow-400">Terms of Service</h1>
        <p className="mb-4">
          Welcome to Archalize. By using our platform, you agree to the following terms and conditions. If you do not agree, please do not use the service.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2 text-yellow-400">1. Use of the Service</h2>
        <p className="mb-4">
          Archalize provides AI-powered architectural critique based on user-uploaded images. You agree to use the platform responsibly and only upload content you have the rights to share.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2 text-yellow-400">2. User Accounts</h2>
        <p className="mb-4">
          You are responsible for maintaining the confidentiality of your login credentials and any activity that occurs under your account.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2 text-yellow-400">3. Intellectual Property</h2>
        <p className="mb-4">
          All content generated by our AI is provided for personal, non-commercial use. Archalize retains ownership of the underlying platform and technology.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2 text-yellow-400">4. Termination</h2>
        <p className="mb-4">
          We reserve the right to terminate access for violations of these terms or misuse of the platform.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2 text-yellow-400">5. Changes</h2>
        <p className="mb-4">
          We may update these terms at any time. Continued use of the service after updates constitutes agreement to the new terms.
        </p>
        <nav className="absolute top-4 left-6 z-10">
          <Link to="/" className="flex items-center gap-2 text-[#1E293B] hover:text-yellow-400 transition">
            <span className="text-2xl">←</span>
            <span className="text-sm font-medium">Home</span>
          </Link>
        </nav>
      </div>
    </div>
  );
}
